name: ForumAA
main: me.furt.ForumAA
version: 2.0
author: TheKris1234, furt
commands:
  account:
    description: Activates forum account.
    usage: |
           To activate your forum account use:
           /<command> activate - Activate Forum Account